name: wechat_ui
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  oktoast: ^2.1.0
  intl: ^0.15.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/welcome_bg.jpg
    - assets/images/welcome_earth.png
    - assets/images/welcome_people.png
    - assets/icons/addfriend_icon_contact.png
    - assets/icons/addfriend_icon_qucikgroup.png
    - assets/icons/addfriend_icon_tag.png
    - assets/icons/addfriend_icon_official.png    
    - assets/icons/headshow1.png    
    - assets/icons/headshow2.png    
    - assets/icons/headshow3.png    
    - assets/icons/headshow4.png    
    - assets/icons/headshow5.png    
    - assets/icons/headshow6.png    
    - assets/icons/ic_sex_female.png    
    - assets/icons/ic_sex_male.png    
    - assets/icons/circle_notreceive.png
    - assets/icons/circle_notvisible.png
    - assets/icons/ofm_moment_icon.png
    - assets/icons/find_more_friend_bottle.png
    - assets/icons/find_more_friend_game.png
    - assets/icons/find_more_friend_near_icon.png
    - assets/icons/find_more_friend_photograph_icon.png
    - assets/icons/find_more_friend_scan.png
    - assets/icons/find_more_friend_shake.png
    - assets/icons/userguide_gamecenter_icon.png
    - assets/icons/ofm_delete_icon.png
    - assets/icons/ofm_remarks_icon.png
    - assets/icons/ofm_reportstop_icon.png
    - assets/icons/ofm_send_icon.png
    - assets/icons/ofm_card_icon.png
    - assets/icons/more_my_favorite.png
    - assets/icons/more_my_album.png
    - assets/icons/more_my_bank_card.png
    - assets/icons/more_emoji_store.png
    - assets/icons/more_setting.png
    - assets/icons/wallet_address_contact_icon.png    
    - assets/icons/addfriend_icon_myqr.png
    
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages